DO $$
DECLARE 
	REV_NUMBER bigint := 0;
BEGIN
	REV_NUMBER :=  nextval('int_uat.LP_REV_INFO_ID_SEQ');
	raise notice 'Value: %', REV_NUMBER;
	
insert into int_uat.REV_INFO (ID,PROCESSED,REVDATE,USERNAME) 
values 
(REV_NUMBER,false,now(),'Super.Admin');

insert into int_uat.lp_human_task_ (LP_HUMAN_TASK_ID, REV, REVTYPE, ACT_TAKEN, ASSIGNED_DT ,ASYNCHRONOUS, COMPLETED_DT, DAYS_FOR_DUE_DT, DUE_DT , ESCALATED_FLAG ,EVENT_NAME , CREATED_AT ,LAST_MODIFIED_AT ,PARENT_TASK ,PROCESS_INSTANCE_ID ,REASSIGN_REASON_CMT, REF_NUM, SESSION_ID,SKIP_REASON,SKIPPABLE ,SOFT_DELETED_ON ,STRT_DT ,SUSPENDED_DT ,SUSPENDED_REASON ,SWIMLANE ,SYS_TASK ,TASK_ACTIONS ,TASK_DESC ,TASK_NAME ,TASK_SESSION_ID,TASK_SUM  ,WRK_ITM_ID,WRK_ITM_PROCESS_ID ,WRK_ITM_PROCESS_INSTANCE_ID,CMT_GRP_ID,ESCALATION_ID,CREATED_BY_USER_ID,LAST_MODIFIED_BY_USER_ID,NTF_CNFG_ID ,OWNER_ID ,PREV_WF_STATUS_ID ,REASSIGN_OWNER_ID ,REASSIGN_REASONS_ID ,REASSIGN_STRATEGY_ID,SUSPEND_REASONS_ID ,TASK_MANAGER_ID ,TASK_PRIORITY_ID,VALIDATING_PAYLOAD_ID,WF_STATUS_ID ,WRK_ITM_PAYLOAD_ID )

select LP_HUMAN_TASK_ID, REV_NUMBER, 0,ACT_TAKEN, ASSIGNED_DT ,ASYNCHRONOUS, COMPLETED_DT, DAYS_FOR_DUE_DT, DUE_DT , ESCALATED_FLAG ,EVENT_NAME , CREATED_AT ,LAST_MODIFIED_AT ,PARENT_TASK ,PROCESS_INSTANCE_ID ,REASSIGN_REASON_CMT, REF_NUM, SESSION_ID,SKIP_REASON,SKIPPABLE ,SOFT_DELETED_ON ,STRT_DT ,SUSPENDED_DT ,SUSPENDED_REASON ,SWIMLANE ,SYS_TASK ,TASK_ACTIONS ,TASK_DESC ,TASK_NAME ,TASK_SESSION_ID,TASK_SUM  ,WRK_ITM_ID,WRK_ITM_PROCESS_ID ,WRK_ITM_PROCESS_INSTANCE_ID,CMT_GRP_ID,ESCALATION_ID,CREATED_BY_USER_ID,LAST_MODIFIED_BY_USER_ID,NTF_CNFG_ID ,OWNER_ID ,PREV_WF_STATUS_ID ,REASSIGN_OWNER_ID ,REASSIGN_REASONS_ID ,REASSIGN_STRATEGY_ID,SUSPEND_REASONS_ID ,TASK_MANAGER_ID ,TASK_PRIORITY_ID,VALIDATING_PAYLOAD_ID,WF_STATUS_ID ,WRK_ITM_PAYLOAD_ID from int_uat.lp_human_task;

insert into int_uat.lp_human_task_pot_tms_ (REV, LP_HUMAN_TASK_ID, LP_TEAM_ID,REVTYPE)
select REV_NUMBER, LP_HUMAN_TASK_ID, LP_TEAM_ID,0 from int_uat.lp_human_task_pot_tms;

                                   
insert into int_uat.lp_human_task_pot_usrs_ (REV,LP_HUMAN_TASK_ID,LP_USER_ID,REVTYPE)
select REV_NUMBER, LP_HUMAN_TASK_ID, LP_USER_ID, 0 from int_uat.lp_human_task_pot_usrs;

insert into int_uat.lp_payload_tp_ (LP_PAYLOAD_TP_ID ,REV ,REVTYPE,PAYLOAD_ENTITY_ID,PAYLOAD_ENTITY_TP,SOFT_DELETED_ON)
select LP_PAYLOAD_TP_ID ,REV_NUMBER ,0,PAYLOAD_ENTITY_ID,PAYLOAD_ENTITY_TP,SOFT_DELETED_ON from int_uat.lp_payload_tp;
END $$;