-----ALTER/ADD columns----
	--LP_NTF_CNFG
	ALTER TABLE int_uat.LP_NTF_CNFG ADD COLUMN EMAIL_ENABLED bool;
	ALTER TABLE int_uat.LP_NTF_CNFG_ ADD COLUMN EMAIL_ENABLED bool;

	--LP_ATTACHMENT
	ALTER TABLE int_uat.LP_ATTACHMENT ADD COLUMN CONTENT_SIZE int4, ADD COLUMN CONTENT_TP varchar(255), ADD COLUMN NAME varchar(255), ADD COLUMN CONTENT_LOB_ID int8;
	ALTER TABLE int_uat.LP_ATTACHMENT_ ADD COLUMN CONTENT_SIZE int4, ADD COLUMN CONTENT_TP varchar(255), ADD COLUMN NAME varchar(255), ADD COLUMN CONTENT_LOB_ID int8;

	--LP_TASK_CNFG
	ALTER TABLE int_uat.LP_TASK_CNFG ADD COLUMN ASYNCHRONOUS bool,ADD COLUMN DUE_DT_EXPRESSION varchar(255), ADD COLUMN TASK_PRIORITY_EXPR varchar(255), ADD COLUMN REASSIGN_STRATEGY_ID int8;
	ALTER TABLE int_uat.LP_TASK_CNFG_ ADD COLUMN ASYNCHRONOUS bool, ADD COLUMN DUE_DT_EXPRESSION varchar(255), ADD COLUMN TASK_PRIORITY_EXPR varchar(255), ADD COLUMN REASSIGN_STRATEGY_ID int8;

	ALTER TABLE int_uat.LP_TASK_CNFG RENAME COLUMN ESCALATION_TO TO ESCALATION_TO_EXPRESSION;
	ALTER TABLE int_uat.LP_TASK_CNFG_ RENAME COLUMN ESCALATION_TO TO ESCALATION_TO_EXPRESSION;

	--LP_TEAM
	ALTER TABLE int_uat.LP_TEAM ADD COLUMN TEAM_MANAGER_ID int8;
	ALTER TABLE int_uat.LP_TEAM_ ADD COLUMN TEAM_MANAGER_ID int8;

	--LP_ADDRESS
	ALTER TABLE int_uat.LP_ADDRESS ADD COLUMN ZIP_EXTENSION varchar(255);
	ALTER TABLE int_uat.LP_ADDRESS_ ADD COLUMN ZIP_EXTENSION varchar(255);

	--LP_ADDRESS
	ALTER TABLE int_uat.LP_ADDRESS ADD COLUMN STATE_ID int8;
	ALTER TABLE int_uat.LP_ADDRESS_ ADD COLUMN STATE_ID int8;
	
	--LP_USER
	ALTER TABLE int_uat.lp_user RENAME COLUMN proxy_end_dttm TO proxy_end_dt ;
	ALTER TABLE int_uat.lp_user_ RENAME COLUMN proxy_end_dttm TO proxy_end_dt ;

	ALTER TABLE int_uat.lp_user RENAME COLUMN proxy_strt_dttm TO proxy_strt_dt ;
	ALTER TABLE int_uat.lp_user_ RENAME COLUMN proxy_strt_dttm TO proxy_strt_dt ;



