package LP_DEFAULT

import com.thirdpillar.codify.loanpath.model.MetaInfo;
import org.apache.commons.lang.StringUtils;
import com.thirdpillar.foundation.model.BaseDataObject;
import com.thirdpillar.codify.loanpath.model.Request;
import com.thirdpillar.codify.loanpath.model.Scoring;
import com.thirdpillar.codify.loanpath.model.Relationship;
import com.thirdpillar.codify.loanpath.model.Facility;
import com.thirdpillar.codify.loanpath.model.Customer;
import com.thirdpillar.codify.loanpath.util.Utility;
import com.thirdpillar.codify.loanpath.model.AttributeChoice;
import com.thirdpillar.foundation.service.LookupService;
import com.thirdpillar.foundation.service.EntityService;
import com.thirdpillar.codify.loanpath.model.FacScoring;
import com.thirdpillar.codify.loanpath.model.*;

import com.thirdpillar.codify.loanpath.constants.Constants;
import com.thirdpillar.codify.loanpath.model.WorkflowStatus;

import function com.thirdpillar.foundation.rules.RuleFunctions.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Date;
import java.math.BigDecimal;
 
rule "Individual : Individual : INDVIDUAL_ATTR_AGE_OF_THE_PARTY"
	agenda-group "CalcScoringAttrIndividual" 
	when
		request : Request()
	then
		Scoring scoring = request.getLatestAppScoring();
		String value="";
		for(PartyScoring partyScoring : scoring.getPartyScorings())
		{
			if(partyScoring.getParty().isIndividual())
			{
				ScoringAttribute attr = partyScoring.findAttributeByKey("INDVIDUAL_ATTR_AGE_OF_THE_PARTY");
				if(partyScoring.getParty().getAgeofCustomer() != null){
					attr.setValue(String.valueOf(partyScoring.getParty().getAgeofCustomer()));
				}
			}		
		}
					
end

rule "Individual : Individual : INDVIDUAL_ATTR_DATE_OF_BIRTH"
	agenda-group "CalcScoringAttrIndividual" 
	when
		request : Request()
	then
		Scoring scoring = request.getLatestAppScoring();
		String value="";
		for(PartyScoring partyScoring : scoring.getPartyScorings())
		{
			if(partyScoring.getParty().isIndividual())
			{
				ScoringAttribute attr = partyScoring.findAttributeByKey("INDVIDUAL_ATTR_DATE_OF_BIRTH");
				if(partyScoring.getParty().getBirthDate() != null){
					attr.setValue(String.valueOf(partyScoring.getParty().getBirthDate()));
				}
			}		
		}
					
end

rule "INDVIDUAL_ATTR_CREDIT_SCORE"
 agenda-group "CalcScoringAttrIndividual" 
    when
          request : Request()
    then
        Scoring scoring = request.getLatestAppScoring();
        for(PartyScoring partyScoring : scoring.getPartyScorings())
		{
			ScoringAttribute attr = partyScoring.findAttributeByKey("INDVIDUAL_ATTR_CREDIT_SCORE");
	        boolean flag = false;
			List<FacilityCustomerRole> borrowerRoles = request.getAllCustomerRolesInRoles("PARTY_ROLE_TYPE_BORROWER");
		 
			List<BureauReport> reports = new ArrayList<BureauReport>();
			int maxFicoScore = 0;
			for (FacilityCustomerRole role : borrowerRoles) {
				Customer customer = null;
				if (role.getCustomer() != null && role.getCustomer().isIndividual()) {
					customer = role.getCustomer();
				} 
				if (customer != null && customer.isIndividual()) {
					Map<String,BureauReport> reportMap = request.getLatestBureauReports(customer);
					for (String reportName : reportMap.keySet()) {
						BureauReport report = reportMap.get(reportName);
						int ficoScore =0;
						if(report.getFicoScore()!=null && !report.getFicoScore().equals("")) {
							ficoScore=Integer.parseInt(report.getFicoScore());
							attr.setValue(String.valueOf(ficoScore));
						}
					}
				}				
			}
			
		}
        
		
end