ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD DROP COLUMN PRNC;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD DROP COLUMN MIN_UTILIZATION;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD DROP COLUMN FNDG_LIMIT;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD DROP COLUMN COMMITMENT_PCT;


ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD_ DROP COLUMN PRNC;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD_ DROP COLUMN MIN_UTILIZATION;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD_ DROP COLUMN FNDG_LIMIT;
ALTER TABLE int_dev.LP_FAC_ALLOCATOR_INT_RCD_ DROP COLUMN COMMITMENT_PCT;
