DROP TABLE int_dev.lp_password_rst_hist;

DROP INDEX int_dev.IDX_LP_PASSWORD_RST_HIST_CREATED_BY_USER_ID;
DROP INDEX int_dev.IDX_LP_PASSWORD_RST_HIST_LAST_MODIFIED_BY_USER_ID;
DROP INDEX int_dev.IDX_LP_PASSWORD_RST_HIST_SOFT_DELETED_ON;

DROP TABLE int_dev.lp_password_rst_hist_;