ALTER TABLE int_dev.LP_FEE_PLC DROP COLUMN EFF_DFLT_FEE_PCT;
ALTER TABLE int_dev.LP_FEE_PLC_ DROP COLUMN EFF_DFLT_FEE_PCT ;


ALTER TABLE int_dev.LP_STRC DROP COLUMN RNW_FEE ;
ALTER TABLE int_dev.LP_STRC_ DROP COLUMN RNW_FEE ;


ALTER TABLE int_dev.LP_FEE_PLC DROP COLUMN PRC_INDEX_ID ;
ALTER TABLE int_dev.LP_FEE_PLC_ DROP COLUMN PRC_INDEX_ID ;

ALTER TABLE int_dev.LP_FEE_PLC DROP COLUMN FEE_CHANGED;
ALTER TABLE int_dev.LP_FEE_PLC_ DROP COLUMN FEE_CHANGED;
