ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP ADD CNTCT_CUST_ID int8;
ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP ADD GUARANTOR_CUST_ID int8;
ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP ADD NON_INDIVIDUAL_CUST_ID int8;
ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP_ ADD CNTCT_CUST_ID int8;
ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP_ ADD GUARANTOR_CUST_ID int8;
ALTER TABLE LOANPATH_OOB_DEV.LP_ONE_STOP_APP_ ADD NON_INDIVIDUAL_CUST_ID int8;

create index IDX_ONE_STOP_CNTCT_CUST on LOANPATH_OOB_DEV.LP_ONE_STOP_APP (CNTCT_CUST_ID);

create index IDX_ONE_STOP_GUARANTOR_CUST on LOANPATH_OOB_DEV.LP_ONE_STOP_APP (GUARANTOR_CUST_ID);

create index IDX_ONE_STOP_NON_INDIVIDUAL_CUST on LOANPATH_OOB_DEV.LP_ONE_STOP_APP (NON_INDIVIDUAL_CUST_ID);

alter table LOANPATH_OOB_DEV.LP_ONE_STOP_APP 
    add constraint FKF4B280F8B044740F 
    foreign key (NON_INDIVIDUAL_CUST_ID) 
    references LOANPATH_OOB_DEV.LP_CUST;

alter table LOANPATH_OOB_DEV.LP_ONE_STOP_APP 
    add constraint FKF4B280F87C2C388F 
    foreign key (GUARANTOR_CUST_ID) 
    references LOANPATH_OOB_DEV.LP_CUST;
    
alter table LOANPATH_OOB_DEV.LP_ONE_STOP_APP 
    add constraint FKF4B280F8E160115E 
    foreign key (CNTCT_CUST_ID) 
    references LOANPATH_OOB_DEV.LP_CUST;        

