ALTER TABLE LP_ATTACHMENT
    ADD ATTACHMENTURL_SIZE number(10,0);
    
ALTER TABLE LP_ATTACHMENT_
    ADD ATTACHMENTURL_SIZE number(10,0);    
    
UPDATE LP_ATTACHMENT SET ATTACHMENTURL_SIZE = dbms_lob.getlength(ATTACHMENTURL) WHERE ATTACHMENTURL  IS NOT NULL;

UPDATE LP_ATTACHMENT_ SET ATTACHMENTURL_SIZE = dbms_lob.getlength(ATTACHMENTURL) WHERE ATTACHMENTURL  IS NOT NULL;
    
ALTER TABLE LP_BUREAU_RPT
    ADD RESPONSE_PDF_SIZE number(10,0);
    
ALTER TABLE LP_BUREAU_RPT_
    ADD RESPONSE_PDF_SIZE number(10,0);    
    
UPDATE LP_BUREAU_RPT SET RESPONSE_PDF_SIZE = dbms_lob.getlength(RESPONSE_PDF) WHERE RESPONSE_PDF  IS NOT NULL;   

UPDATE LP_BUREAU_RPT_ SET RESPONSE_PDF_SIZE = dbms_lob.getlength(RESPONSE_PDF) WHERE RESPONSE_PDF  IS NOT NULL; 
    
ALTER TABLE LP_DOC
    ADD (
        ARCHIVE_STREAM_SIZE number(10,0),
        SIGNING_METADATA_SIZE number(10,0),
        UPLOADED_STREAM_SIZE number(10,0)
    );
    
    
ALTER TABLE LP_DOC_
    ADD (
        ARCHIVE_STREAM_SIZE number(10,0),
        SIGNING_METADATA_SIZE number(10,0),
        UPLOADED_STREAM_SIZE number(10,0)
    );
    
UPDATE LP_DOC SET ARCHIVE_STREAM_SIZE = dbms_lob.getlength(ARCHIVE_STREAM) WHERE ARCHIVE_STREAM  IS NOT NULL;
UPDATE LP_DOC SET SIGNING_METADATA_SIZE = dbms_lob.getlength(SIGNING_METADATA) WHERE SIGNING_METADATA  IS NOT NULL;
UPDATE LP_DOC SET UPLOADED_STREAM_SIZE = dbms_lob.getlength(UPLOADED_STREAM) WHERE UPLOADED_STREAM  IS NOT NULL;
    
UPDATE LP_DOC_ SET ARCHIVE_STREAM_SIZE = dbms_lob.getlength(ARCHIVE_STREAM) WHERE ARCHIVE_STREAM  IS NOT NULL;
UPDATE LP_DOC_ SET SIGNING_METADATA_SIZE = dbms_lob.getlength(SIGNING_METADATA) WHERE SIGNING_METADATA  IS NOT NULL;
UPDATE LP_DOC_ SET UPLOADED_STREAM_SIZE = dbms_lob.getlength(UPLOADED_STREAM) WHERE UPLOADED_STREAM  IS NOT NULL;
            
ALTER TABLE LP_ICON_LIBRARY
    ADD ICON_FILE_SIZE number(10,0);
    
ALTER TABLE LP_ICON_LIBRARY_
    ADD ICON_FILE_SIZE number(10,0);    
    
UPDATE LP_ICON_LIBRARY SET ICON_FILE_SIZE = dbms_lob.getlength(ICON_FILE) WHERE ICON_FILE  IS NOT NULL;   

UPDATE LP_ICON_LIBRARY_ SET ICON_FILE_SIZE = dbms_lob.getlength(ICON_FILE) WHERE ICON_FILE  IS NOT NULL;     
    
ALTER TABLE LP_INTEGRATION_TASK_LOG
    ADD XML_PAYLOAD_SIZE number(10,0);
    
ALTER TABLE LP_INTEGRATION_TASK_LOG_
    ADD XML_PAYLOAD_SIZE number(10,0);    
    
UPDATE LP_INTEGRATION_TASK_LOG SET XML_PAYLOAD_SIZE = dbms_lob.getlength(XML_PAYLOAD) WHERE XML_PAYLOAD  IS NOT NULL;   

UPDATE LP_INTEGRATION_TASK_LOG_ SET XML_PAYLOAD_SIZE = dbms_lob.getlength(XML_PAYLOAD) WHERE XML_PAYLOAD  IS NOT NULL;         
    
ALTER TABLE LP_MOODY_PARTY_FINC_INFO
    ADD  FINC_SUM_SIZE number(10,0);
    
ALTER TABLE LP_MOODY_PARTY_FINC_INFO_
    ADD  FINC_SUM_SIZE number(10,0);    
    
UPDATE LP_MOODY_PARTY_FINC_INFO SET FINC_SUM_SIZE = dbms_lob.getlength(FINC_SUM) WHERE FINC_SUM  IS NOT NULL;   

UPDATE LP_MOODY_PARTY_FINC_INFO_ SET FINC_SUM_SIZE = dbms_lob.getlength(FINC_SUM) WHERE FINC_SUM  IS NOT NULL;     
    
ALTER TABLE LP_PAGE_AS_IMAGE
    ADD IMAGE_SIZE number(10,0);
    
ALTER TABLE LP_PAGE_AS_IMAGE_
    ADD IMAGE_SIZE number(10,0);        
    
UPDATE LP_PAGE_AS_IMAGE SET IMAGE_SIZE = dbms_lob.getlength(IMAGE) WHERE IMAGE  IS NOT NULL;   

UPDATE LP_PAGE_AS_IMAGE_ SET IMAGE_SIZE = dbms_lob.getlength(IMAGE) WHERE IMAGE  IS NOT NULL;      
    
ALTER TABLE LP_SCRCRD_DTL
    ADD AUDIT_RESP_XML_SIZE number(10,0);
    
ALTER TABLE LP_SCRCRD_DTL_
    ADD AUDIT_RESP_XML_SIZE number(10,0);  
    
UPDATE LP_SCRCRD_DTL SET AUDIT_RESP_XML_SIZE = dbms_lob.getlength(AUDIT_RESP_XML) WHERE AUDIT_RESP_XML  IS NOT NULL;     

UPDATE LP_SCRCRD_DTL_ SET AUDIT_RESP_XML_SIZE = dbms_lob.getlength(AUDIT_RESP_XML) WHERE AUDIT_RESP_XML  IS NOT NULL;            
    
ALTER TABLE LP_TEST_ENTITY
    ADD IMAGE_SIZE number(10,0);
    
ALTER TABLE LP_TEST_ENTITY_
    ADD IMAGE_SIZE number(10,0);      
    
UPDATE LP_TEST_ENTITY SET IMAGE_SIZE = dbms_lob.getlength(IMAGE) WHERE IMAGE  IS NOT NULL;   

UPDATE LP_TEST_ENTITY_ SET IMAGE_SIZE = dbms_lob.getlength(IMAGE) WHERE IMAGE  IS NOT NULL;       
    
ALTER TABLE LP_UCC_ATTACHMENT
    ADD ATTACHMENT_BIN_VAL_SIZE number(10,0);
    
ALTER TABLE LP_UCC_ATTACHMENT_
    ADD ATTACHMENT_BIN_VAL_SIZE number(10,0);
    
UPDATE LP_UCC_ATTACHMENT SET ATTACHMENT_BIN_VAL_SIZE = dbms_lob.getlength(ATTACHMENT_BIN_VAL) WHERE ATTACHMENT_BIN_VAL IS NOT NULL;   

UPDATE LP_UCC_ATTACHMENT_ SET ATTACHMENT_BIN_VAL_SIZE = dbms_lob.getlength(ATTACHMENT_BIN_VAL) WHERE ATTACHMENT_BIN_VAL IS NOT NULL;       

commit;