ALTER TABLE LP_RQ MODIFY APP_MOD_DTTM timestamp;
ALTER TABLE LP_RQ MODIFY FNL_DCSN timestamp;
ALTER TABLE LP_RQ MODIFY REGB_DTTM timestamp;

ALTER TABLE LP_RQ_ MODIFY APP_MOD_DTTM timestamp;
ALTER TABLE LP_RQ_ MODIFY FNL_DCSN timestamp;
ALTER TABLE LP_RQ_ MODIFY REGB_DTTM timestamp;