<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsl">
	<xsl:output method="xml" encoding="UTF-8" indent="yes" omit-xml-declaration="no"/>
	<xsl:template match="*">
		<customer>
    <commentGroup>
      <comments/>
      <id>2</id>
    </commentGroup>
    <documentPackages/>
    <id>1</id>
    <partyDetail>
      <CGRqrdForPrmitdLesses>false</CGRqrdForPrmitdLesses>
      <UCCs/>
      <accountName></accountName>
      <applicationRequireFlag>false</applicationRequireFlag>
      <authorizedToEsign>false</authorizedToEsign>
      <bankAccounts/>
      <birthCity></birthCity>
      <bureauReports/>
      <businessChannel></businessChannel>
      <classification/>
      <compliances/>
      <contactTypeDetails/>
      <creditHoldFlag>false</creditHoldFlag>
      <currentlyDelinquent>false</currentlyDelinquent>
      <dbas/>
      <deleted>false</deleted>
      <delistedFlag>false</delistedFlag>
      <disclosePersonalInfo>false</disclosePersonalInfo>
      <extIdentifiers/>
      <firstName></firstName>
      <foreignUseRiders/>
      <fraudAlerts/>
      <freezeFlag>false</freezeFlag>
      <healthcareCompanyFlag>false</healthcareCompanyFlag>
      <holds/>
      <id>3</id>
      <insurance>
        <agentContactName></agentContactName>
        <agentName></agentName>
        <agentPhone></agentPhone>
        <comments></comments>
        <id>4</id>
        <insuranceDetail>
          <id>5</id>
          <insuranceCarier></insuranceCarier>
          <policyNumber></policyNumber>
        </insuranceDetail>
      </insurance>
      <japaneseCompanyFlag>false</japaneseCompanyFlag>
      <lastName></lastName>
      <legalName></legalName>
      <losResolved>false</losResolved>
      <medicalOrDentalParty>false</medicalOrDentalParty>
      <organizationNumber></organizationNumber>
      <originalParty>false</originalParty>
      <partyClassifications/>
      <partyContactDetails/>
      <partyDetailQuestionaires/>
      <partyLiabilities/>
      <partyMoodyFinancialAssocs/>
      <partyOwnedAssets/>
      <priorLossOrChargeOff>false</priorLossOrChargeOff>
      <relatedParties/>
      <riskRatings/>
      <sites/>
      <subsidiaryFlag>false</subsidiaryFlag>
      <taxExemptFlag>false</taxExemptFlag>
      <users/>
      <status>
        <key>ACTIVE_INACTIVE_STATUS_ACTIVE</key>
        <value>Active</value>
      </status>
    </partyDetail>
    <refNumber>100000</refNumber>
  </customer>
	</xsl:template>
</xsl:stylesheet>
